---
parser: '@babel/eslint-parser'

plugins:
  - react
  - functional

extends:
  - airbnb
  - 'plugin:functional/external-recommended'
  - 'plugin:functional/recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'

env:
  browser: true
  node: true

rules:
  import/extensions: 0
  # TODO: cause an error
  import/no-unresolved: 0
  react/prop-types: 0
  no-console: 0
  functional/no-conditional-statement: 0
  functional/no-expression-statement: 0
  functional/immutable-data: 0
  functional/functional-parameters: 0
  functional/no-try-statement: 0
  functional/no-throw-statement: 0
  no-underscore-dangle: [2, { 'allow': ['__filename', '__dirname'] }]
  testing-library/no-debug: 0
  react/jsx-filename-extension: [1, { 'extensions': ['.js', '.jsx'] }]
